import { useEffect, useMemo, useState } from "react";
import WalletWorkspace from "./WalletWorkspace";
import WebsiteDetailPage from "./WebsiteDetailPage";
import { useNotifications } from "./NotificationSystem";

function MiniIcon({ name, size = 17 }) {
  const props = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true" };
  const paths = {
    plus: <><path d="M12 5v14M5 12h14" /></>, globe: <><circle cx="12" cy="12" r="9" /><path d="M3 12h18M12 3a14 14 0 0 1 0 18" /></>,
    code: <><path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14" /></>, link: <><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1" /><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 7 20l1.1-1.1" /></>,
    copy: <><rect x="8" y="8" width="11" height="12" rx="2" /><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h2" /></>, check: <path d="m5 12 4 4L19 6" />, arrow: <path d="m9 18 6-6-6-6" />, eye: <><path d="M2.5 12s3.5-5 9.5-5 9.5 5 9.5 5-3.5 5-9.5 5-9.5-5-9.5-5Z" /><circle cx="12" cy="12" r="2.2" /></>, wallet: <><path d="M4 6h15a2 2 0 0 1 2 2v11H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14" /><path d="M16 13h5" /><circle cx="16" cy="13" r=".5" /></>, clock: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></>, trend: <><path d="M3 17 9 11l4 4 8-9" /><path d="M16 6h5v5" /></>, chart: <><path d="M4 20V10M11 20V4M18 20v-7" /></>,
  };
  return <svg {...props}>{paths[name] || paths.plus}</svg>;
}
function PageHeader({ title, description, action, onAction, icon = "plus", eyebrow = "PUBLISHER / INVENTORY", aside }) { return <div className="workspace-page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{aside || action && <button className="primary-button" type="button" onClick={onAction}><MiniIcon name={icon} size={17} />{action}</button>}</div>; }
function EmptyState({ icon = "globe", title, description, action, onAction }) { return <div className="empty-state"><span className="empty-state-icon"><MiniIcon name={icon} size={25} /></span><h2>{title}</h2><p>{description}</p>{action && <button className="secondary-button" type="button" onClick={onAction}><MiniIcon name="plus" size={16} />{action}</button>}</div>; }
function Field({ label, hint, error, children }) { return <label className="field"><span>{label}</span>{children}{hint && !error && <small>{hint}</small>}{error && <small className="field-error">{error}</small>}</label>; }
const blankWebsite = { name: "", url: "" };
function WebsiteForm({ form, setForm, errors, onCancel, onSubmit }) { const update = (key, value) => setForm(previous => ({ ...previous, [key]: value })); return <section className="form-panel light-panel"><div className="panel-heading"><div><span className="eyebrow">PUBLISHER / WEBSITE</span><h2>Add website</h2></div><button className="link-button" type="button" onClick={onCancel}>Cancel</button></div><p className="form-intro">أدخل Website Name وWebsite URL فقط. لا يختار الناشر نوع الإعلان أو الـCreative أو الحجم.</p><div className="form-grid"><Field label="Website Name" error={errors.name}><input className="input" value={form.name} onChange={event => update("name", event.target.value)} placeholder="My website" /></Field><Field label="Website URL" hint="Use a full HTTPS address" error={errors.url}><input className="input" type="url" value={form.url} onChange={event => update("url", event.target.value)} placeholder="https://example.com" /></Field></div><div className="form-actions"><button className="primary-button" type="button" onClick={onSubmit}><MiniIcon name="check" size={16} />Add website</button><button className="ghost-button" type="button" onClick={onCancel}>Cancel</button></div></section>; }

function WebsitesPage({ data, setData, onNavigate, onDetails }) {
  const { notify } = useNotifications();
  const [showForm, setShowForm] = useState(data.websites.length === 0); const [form, setForm] = useState(blankWebsite); const [errors, setErrors] = useState({});
  const addWebsite = () => { const next = {}; if (!form.name.trim()) next.name = "Enter a website name."; const normalized = form.url.trim().startsWith("http") ? form.url.trim() : "https://" + form.url.trim(); try { const parsed = new URL(normalized); if (parsed.protocol !== "https:" || !parsed.hostname.includes(".")) next.url = "Enter a valid HTTPS website address."; } catch { next.url = "Enter a valid HTTPS website address."; } setErrors(next); if (Object.keys(next).length) return; const website = { id: "website-" + Date.now(), name: form.name.trim(), url: new URL(normalized).toString(), status: "Pending", dateAdded: new Date().toLocaleDateString("en-US"), impressions: 0, clicks: 0 }; setData(previous => ({ ...previous, websites: [...previous.websites, website] })); setForm(blankWebsite); setErrors({}); setShowForm(false); notify("Website added. Your Universal AdZora Code is ready.", "success"); onNavigate("websites"); };
  return <div className="workspace-page"><PageHeader title="My Websites" description="أضف Website Name وWebsite URL فقط. احصل على Universal AdZora Code ثم راقب أداء موقعك من Analytics." action="Add Website" onAction={() => setShowForm(true)} />{showForm && <WebsiteForm form={form} setForm={setForm} errors={errors} onCancel={() => { setShowForm(false); setErrors({}); }} onSubmit={addWebsite} />}{!data.websites.length && !showForm ? <section className="light-panel"><EmptyState title="No websites yet" description="أضف موقعك للحصول على Universal AdZora Code ومتابعة التحليلات." action="Add Website" onAction={() => setShowForm(true)} /></section> : data.websites.length > 0 && <section className="light-panel data-panel"><div className="panel-heading"><div><span className="eyebrow">PUBLISHER WEBSITES</span><h2>{data.websites.length} website{data.websites.length === 1 ? "" : "s"}</h2></div><span className="result-count">Universal code ready</span></div><div className="publisher-site-grid">{data.websites.map(website => <article className="publisher-site-card" key={website.id}><button className="publisher-site-open" type="button" onClick={() => onDetails(website.id)} aria-label={`Open ${website.name} details`}><div className="publisher-site-heading"><div className="publisher-site-identity"><strong>{website.name}</strong><span>{website.url}</span></div><span className="status-badge pending">{website.status}</span></div></button><div className="publisher-website-actions"><button className="primary-button universal-code-button" type="button" onClick={() => onNavigate("ad-codes")}><MiniIcon name="code" size={16} />Universal Code</button><button className="secondary-button" type="button" onClick={() => onNavigate("analytics", website.id)}><MiniIcon name="trend" size={16} />Analytics</button><button className="icon-button website-view-details" type="button" onClick={() => onDetails(website.id)} aria-label={`View details for ${website.name}`}><MiniIcon name="arrow" size={16} /></button></div></article>)}</div></section>}</div>;
}

function AdCodesPage({ data, onNavigate }) {
  const { notify } = useNotifications();
  const [copiedId, setCopiedId] = useState(""); const codeFor = website => "<!-- AdZora Universal Code -->" + String.fromCharCode(10) + "<script src=\"https://ad-zora.vercel.app/ad.js\" data-adzora-website=\"" + website.id + "\" async></script>";
  const copyCode = async website => { try { await navigator.clipboard.writeText(codeFor(website)); setCopiedId(website.id); notify("Universal AdZora Code copied.", "success"); setTimeout(() => setCopiedId(""), 1800); } catch { notify("Copy is unavailable in this browser.", "error"); } };
  return <div className="workspace-page"><PageHeader title="Universal AdZora Code" description="انسخ كودًا واحدًا إلى موقعك. الناشر لا يختار Campaign أو Creative أو Image أو Video أو Ad Size." action="Add Website" onAction={() => onNavigate("websites")} />{!data.websites.length ? <section className="light-panel"><EmptyState icon="code" title="Add a website first" description="بعد إضافة Website Name وWebsite URL سيظهر Universal AdZora Code هنا." action="Add Website" onAction={() => onNavigate("websites")} /></section> : <div className="code-list">{data.websites.map(website => <section className="light-panel code-card" key={website.id}><div className="code-card-heading"><div className="row-main"><span className="row-icon"><MiniIcon name="code" /></span><div><strong>{website.name}</strong><small>{website.url}</small></div></div><span className="status-badge ready">Universal</span></div><div className="code-note"><strong>One universal code for this website</strong><span>Ad Server will choose an eligible campaign and Creative later. Publisher settings do not include ad type, size, or Creative.</span></div><pre className="code-box"><code>{codeFor(website)}</code></pre><div className="code-actions"><button className="primary-button universal-code-button" type="button" onClick={() => copyCode(website)}><MiniIcon name={copiedId === website.id ? "check" : "copy"} size={16} />{copiedId === website.id ? "Copied" : "Copy Universal Code"}</button><button className="ghost-button" type="button" onClick={() => onNavigate("websites")}><MiniIcon name="globe" size={16} />Manage website</button></div><div className="code-install-note" role="note"><strong>ملاحظة</strong><span>ضع هذا الكود داخل وسم <code>&lt;head&gt;</code> في موقعك لتفعيل خدمة الإعلانات.</span></div></section>)}</div>}</div>;
}

function FinanceMetrics({ finance }) { const metrics = [["Available Earnings", finance.available, "wallet"], ["Pending Earnings", finance.pending, "clock"], ["Total Earned", finance.earned, "trend"], ["Withdrawn", finance.withdrawn, "trend"]]; return <section className="metric-grid financial-metrics">{metrics.map(([label, value, icon]) => <article className="metric-card" key={label}><div className="metric-top"><span className="metric-icon"><MiniIcon name={icon} size={16} /></span><span className="metric-label">{label}</span></div><strong className="metric-value">{"$"}{value.toFixed(2)}</strong></article>)}</section>; }
function EarningsPage({ finance, onNavigate }) { return <div className="workspace-page"><PageHeader title="Publisher Earnings" description="تابع أرباح الناشر منفصلة عن Advertiser Spend من مكان واحد." action="Withdraw earnings" onAction={() => onNavigate("withdrawals")} icon="arrow" /><FinanceMetrics finance={finance} /><section className="light-panel"><div className="panel-heading"><div><span className="eyebrow">TRACKING</span><h2>Publisher revenue events</h2></div></div><div className="event-chip-list"><span>Impression</span><span>Click</span><span>Video View</span></div><p className="muted-copy">تُستخدم هذه الأحداث لاحتساب أرباحك تلقائيًا فور بدء استقبال الزيارات المؤهلة.</p></section></div>; }
function WithdrawalsPage({ finance, withdrawals, setFinance, setWithdrawals }) { const { notify } = useNotifications(); const [amount, setAmount] = useState(""); const [error, setError] = useState(""); const submit = () => { const value = Number(amount); if (!value || value < finance.minimum) { setError("The amount is below the minimum withdrawal."); return; } if (value > finance.available) { setError("The amount exceeds available earnings."); return; } const item = { id: "withdrawal-" + Date.now(), amount: value, status: "Pending", date: new Date().toLocaleDateString("en-US") }; setFinance(previous => ({ ...previous, available: previous.available - value })); setWithdrawals(previous => [...previous, item]); setAmount(""); setError(""); notify("Your withdrawal request has been submitted and is now pending review.", "success"); }; return <div className="workspace-page"><PageHeader title="Withdrawals" description="أدر طلبات سحب أرباحك بشكل منفصل عن إنفاق المعلن." /><section className="form-panel light-panel"><div className="withdraw-balance"><span>Available Earnings</span><strong>{"$"}{finance.available.toFixed(2)}</strong><small>Minimum: {"$"}{finance.minimum.toFixed(2)}</small></div><div className="form-grid"><Field label="Amount" error={error}><input className="input" type="number" value={amount} min={finance.minimum} onChange={event => { setAmount(event.target.value); setError(""); }} placeholder="50" /></Field><Field label="Payment method"><select className="input select"><option>Bank transfer</option><option>Manual review</option></select></Field></div><button className="primary-button" type="button" onClick={submit}><MiniIcon name="check" size={16} />Submit Withdrawal Request</button></section><section className="light-panel"><div className="panel-heading"><div><span className="eyebrow">WITHDRAWAL STATUS</span><h2>Recent requests</h2></div><span className="result-count">{withdrawals.length} records</span></div>{!withdrawals.length ? <EmptyState icon="trend" title="No withdrawals yet" description="ستظهر طلبات السحب هنا بمجرد إنشائها." /> : <div className="data-list">{withdrawals.map(item => <div className="data-row compact-finance-row" key={item.id}><div className="row-main"><span className="row-icon"><MiniIcon name="trend" /></span><div><strong>{"$"}{item.amount.toFixed(2)}</strong><small>{item.date}</small></div></div><span className="status-badge pending">{item.status}</span></div>)}</div>}</section></div>; }

const formatLabels = { native: "Native", social: "Social", video: "Video" };
const periodOptions = ["Today", "7 Days", "30 Days", "90 Days"];

function getWebsiteDomain(url) {
  try { return new URL(url).hostname; } catch { return url; }
}

function formatAnalyticsNumber(value) {
  return Number(value || 0).toLocaleString("en-US");
}

function formatAnalyticsMoney(value) {
  return "$" + Number(value || 0).toFixed(2);
}

function computeCtr(impressions, clicks) {
  if (!impressions) return "--";
  return ((clicks / impressions) * 100).toFixed(2) + "%";
}

// Builds a website's analytics summary strictly from real stored fields (impressions,
// clicks). There is no synthetic/demo dataset here: a website with no recorded activity
// shows zero metrics and an explicit empty state instead of invented numbers.
function buildWebsiteAnalytics(website) {
  const impressions = website.impressions || 0;
  const clicks = website.clicks || 0;
  return {
    ...website,
    websiteId: website.id,
    domain: getWebsiteDomain(website.url),
    status: website.status || "Pending",
    impressions,
    clicks,
    ctr: computeCtr(impressions, clicks),
    hasActivity: impressions > 0,
  };
}

function AnalyticsMetric({ label, value, icon }) {
  return <article className="metric-card analytics-metric"><div className="metric-top"><span className="metric-icon"><MiniIcon name={icon} size={16} /></span><span className="metric-label">{label}</span></div><strong className="metric-value">{value}</strong></article>;
}

function WebsitePerformanceCard({ website, onDetails }) {
  const metrics = [["Impressions", formatAnalyticsNumber(website.impressions)], ["Clicks", formatAnalyticsNumber(website.clicks)], ["CTR", website.ctr]];
  return <article className="website-analytics-card"><div className="website-analytics-card-header"><div className="website-analytics-identity"><strong>{website.name}</strong><span>{website.domain}</span></div><span className={"status-badge " + (website.status === "Active" ? "ready" : "pending")}>{website.status}</span></div><div className="website-analytics-metrics">{metrics.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{!website.hasActivity && <p className="muted-copy analytics-card-note">No analytics yet — this website has not received tracked activity.</p>}<button className="secondary-button website-details-button" type="button" onClick={() => onDetails(website.websiteId)}><MiniIcon name="eye" size={15} />View Details</button></article>;
}

function WebsiteAnalyticsDetail({ website, websites, onSelectWebsite, onBack }) {
  return <section className="website-analytics-detail"><div className="detail-header"><button className="link-button" type="button" onClick={onBack}><MiniIcon name="arrow" size={15} />Back to Analytics</button><label className="field analytics-select"><span>Website</span><select className="input select" value={website.websiteId} onChange={event => onSelectWebsite(event.target.value)}><option value="all">All Websites</option>{websites.map(item => <option key={item.websiteId} value={item.websiteId}>{item.name}</option>)}</select></label></div><section className="light-panel selected-website-summary"><div><h2>{website.name}</h2><p>{website.domain} · <span className={website.status === "Active" ? "status-text-active" : "status-text-pending"}>{website.status}</span></p></div></section><section className="analytics-metric-grid detail-metrics">{[["Impressions", formatAnalyticsNumber(website.impressions), "eye"], ["Clicks", formatAnalyticsNumber(website.clicks), "trend"], ["CTR", website.ctr, "chart"], ["Earnings", formatAnalyticsMoney(website.earnings || 0), "wallet"]].map(([label, value, icon]) => <AnalyticsMetric key={label} label={label} value={value} icon={icon} />)}</section><section className="light-panel publisher-performance-panel"><div className="panel-heading"><div><h2>{website.name} performance</h2></div></div>{website.hasActivity ? <p className="muted-copy">Performance charts will populate here once the tracking endpoint reports real events for this website.</p> : <div className="chart-empty-state static-empty"><span className="chart-empty-icon"><MiniIcon name="trend" size={18} /></span><strong>No analytics yet</strong><span>Add the Universal AdZora Code to this website and verify it to start collecting impressions and clicks.</span></div>}</section><section className="light-panel ad-format-panel"><div className="panel-heading"><div><h2>Ad Format Performance</h2></div><span className="phase-chip">Native · Social · Video</span></div><div className="chart-empty-state static-empty format-empty-note"><span className="chart-empty-icon"><MiniIcon name="chart" size={18} /></span><strong>No format breakdown yet</strong><span>Once campaigns start delivering on this website, performance will be split by Native, Social, and Video here.</span></div></section></section>;
}

function PublisherAnalyticsPage({ data, finance, onNavigate, selectedWebsiteId = "" }) {
  const [selectedId, setSelectedId] = useState(selectedWebsiteId);
  const websites = data.websites || [];
  useEffect(() => { if (selectedWebsiteId) setSelectedId(selectedWebsiteId); }, [selectedWebsiteId]);
  const websiteAnalytics = websites.map(buildWebsiteAnalytics);
  const selectedWebsite = websiteAnalytics.find(website => website.websiteId === selectedId);
  const totalImpressions = websiteAnalytics.reduce((sum, item) => sum + item.impressions, 0);
  const totalClicks = websiteAnalytics.reduce((sum, item) => sum + item.clicks, 0);
  const summaryMetrics = [
    ["Impressions", formatAnalyticsNumber(totalImpressions), "eye"],
    ["Clicks", formatAnalyticsNumber(totalClicks), "trend"],
    ["CTR", computeCtr(totalImpressions, totalClicks), "chart"],
    ["Total Earned", formatAnalyticsMoney(finance.earned), "wallet"],
  ];
  if (selectedWebsite) return <div className="workspace-page publisher-analytics"><PageHeader eyebrow="PUBLISHER / ANALYTICS" title="Analytics" description="Track your websites, ad performance, and earnings." /><WebsiteAnalyticsDetail website={selectedWebsite} websites={websiteAnalytics} onSelectWebsite={id => id === "all" ? setSelectedId("") : setSelectedId(id)} onBack={() => setSelectedId("")} /></div>;
  return <div className="workspace-page publisher-analytics">
    <PageHeader eyebrow="PUBLISHER / ANALYTICS" title="Analytics" description="Track your websites, ad performance, and earnings." />
    <section className="analytics-metric-grid publisher-analytics-metrics">{summaryMetrics.map(([label, value, icon]) => <AnalyticsMetric key={label} label={label} value={value} icon={icon} />)}</section>
    <section className="light-panel earnings-summary-panel"><div className="panel-heading"><div><h2>Earnings overview</h2></div></div><div className="earnings-summary-grid"><div><span>Available Earnings</span><strong>{formatAnalyticsMoney(finance.available)}</strong></div><div><span>Pending Earnings</span><strong>{formatAnalyticsMoney(finance.pending)}</strong></div><div><span>Total Earned</span><strong>{formatAnalyticsMoney(finance.earned)}</strong></div><div><span>Total Withdrawn</span><strong>{formatAnalyticsMoney(finance.withdrawn)}</strong></div></div></section>
    <section className="light-panel website-performance-panel"><div className="panel-heading"><div><span className="eyebrow">PUBLISHER INVENTORY</span><h2>Websites Performance</h2></div><button className="text-button" type="button" onClick={() => onNavigate("websites")}>Manage websites <MiniIcon name="arrow" size={14} /></button></div>{!websiteAnalytics.length ? <EmptyState icon="globe" title="No websites yet" description="Add a website to start receiving AdZora ads and analytics." action="Add Website" onAction={() => onNavigate("websites")} /> : <div className="website-analytics-grid">{websiteAnalytics.map(website => <WebsitePerformanceCard website={website} key={website.websiteId} onDetails={setSelectedId} />)}</div>}</section>
    {!totalImpressions && websiteAnalytics.length > 0 && <section className="light-panel activity-panel"><div className="panel-heading"><div><h2>Recent Activity</h2></div></div><div className="empty-state compact-empty"><MiniIcon name="clock" size={22} /><h2>No activity yet</h2><p>Activity will appear here once your websites start receiving tracked impressions and clicks.</p></div></section>}
  </div>;
}

function PublisherTransactions({ withdrawals }) { return <div className="workspace-page"><PageHeader title="Publisher Transactions" description="سجل منفصل لأرباح الناشر والتعديلات والسحوبات، دون خلطه بإنفاق المعلن." /><section className="light-panel data-panel"><div className="panel-heading"><div><span className="eyebrow">TRANSACTION HISTORY</span><h2>{withdrawals.length} records</h2></div></div>{!withdrawals.length ? <EmptyState icon="code" title="No transactions yet" description="ستظهر Earnings وAdjustments وWithdrawals هنا عند وجود بيانات." /> : <div className="data-list">{withdrawals.map(item => <div className="data-row" key={item.id}><div className="row-main"><span className="row-icon"><MiniIcon name="trend" /></span><div><strong>Withdrawal · {"$"}{item.amount.toFixed(2)}</strong><small>{item.date}</small></div></div><span className="status-badge pending">{item.status}</span></div>)}</div>}</section></div>; }
export default function PublisherWorkspace({ page, data, setData, onNavigate, selectedWebsiteId = "", finance = { available: 0, pending: 0, earned: 0, withdrawn: 0, minimum: 50 }, setFinance = () => {}, withdrawals = [], setWithdrawals = () => {} }) { const content = useMemo(() => page, [page]); const selectedWebsite = data.websites?.find(website => website.id === selectedWebsiteId); const selectedIndex = data.websites?.findIndex(website => website.id === selectedWebsiteId) ?? 0; return <div className="publisher-workspace">{content === "websites" && <WebsitesPage data={data} setData={setData} onNavigate={onNavigate} onDetails={id => onNavigate("website-details", id)} />}{content === "website-details" && <WebsiteDetailPage website={selectedWebsite} websiteIndex={selectedIndex < 0 ? 0 : selectedIndex} onBack={() => onNavigate("websites")} onAnalytics={id => onNavigate("analytics", id)} />}{content === "ad-codes" && <AdCodesPage data={data} onNavigate={onNavigate} />}{content === "earnings" && <EarningsPage finance={finance} onNavigate={onNavigate} />}{content === "withdrawals" && <WalletWorkspace mode="withdrawal" requests={withdrawals} setRequests={setWithdrawals} available={finance.available} />}{content === "transactions" && <PublisherTransactions withdrawals={withdrawals} />}{content === "analytics" && <PublisherAnalyticsPage data={data} finance={finance} onNavigate={onNavigate} selectedWebsiteId={selectedWebsiteId} />}</div>; }
